- name: download the source code for Mozilla SpiderMonkey 1.85
  get_url: url=http://ftp.mozilla.org/pub/mozilla.org/js/js185-1.0.0.tar.gz dest=/tmp

- name: unarchive the tar file
  shell: chdir=/tmp tar -xzf js185-1.0.0.tar.gz

- name: compile Mozilla SpiderMonkey 1.8.5
  shell: chdir=/tmp/js-1.8.5/js/src {{ item }}
  with_items:
  - ./configure
  - make --silent
  - make DESTDIR=fpm --silent install

- name: fix the libmozjs185.so.1.0 symlink
  file: state=link path=/tmp/js-1.8.5/js/src/fpm/usr/local/lib/libmozjs185.so.1.0 src=libmozjs185.so.1.0.0 force=yes
  tags: fix_symlink1

- name: fix the libmozjs185.so symlink
  file: state=link path=/tmp/js-1.8.5/js/src/fpm/usr/local/lib/libmozjs185.so src=libmozjs185.so.1.0 force=yes
  tags: fix_symlink2

- name: package Mozilla SpiderMonkey 1.8.5 as an rpm with fpm
  shell: fpm -s dir -t rpm -n js -v 1.85 -f -p {{ RPMS_DIRECTORY }} -C /tmp/js-1.8.5/js/src/fpm/ usr

#- name: install SpiderMonkey from the RPM file (this is required in order to compile CouchDB)
#  yum: name={{ RPMS_DIRECTORY }}/js-1.85-1.x86_64.rpm

#- name: add the symbolic link /usr/include/js pointing to /usr/local/include/js (otherwise CouchDB complains about not being able to find jsapi.h)
#  file: path=/usr/include/js src=/usr/local/include/js state=link

#- name: add a ld.so config for the folder /usr/local/lib
#  copy: src=usrlocal.conf dest=/etc/ld.so.conf.d/usrlocal.conf

#- name: run ldconfig
#  shell: /sbin/ldconfig
